# <editor-fold desc="XML DATA">


XML_FILE_TEMPLATE = '''<?xml version="1.0" encoding="UTF-8"?>
<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
\tmlns:cim="http://iec.ch/TC57/2010/CIM-schema-cim15#"
\txmlns:ftn="http://www.ftnydro.com/CIM15/2010/extension#">
<!-- generated by: 'CIMET' application -->{{data}}

</rdf:RDF>'''
DATA_POINT_TEMPLATE = '''
\t<cim:{{class_name}} rdf:ID="{{class_id}}">
{{class_data}}
\t</cim:{{class_name}}>'''

# </editor-fold>
