models = {
    'IdentifiedObject': [
        ('abstract', 'type'),
        ('', 'inheritance'),
        ('gid', 'long'),
        ('mRID', 'string'),
        ('aliasName', 'string'),
        ('name', 'string')
    ],
    'PowerSystemResource': [
        ('abstract', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('OutageSchedules', 'reflist'),
    ],
    'Equipment': [
        ('abstract', 'type'),
        ('PowerSystemResource', 'inheritance'),
        ('aggregate', 'bool'),
        ('normallyInService', 'bool'),
    ],
    'ConductingEquipment': [
        ('abstract', 'type'),
        ('Equipment', 'inheritance'),
        ('Terminals', 'reflist'),
    ],
    'Switch': [
        ('abstract', 'type'),
        ('ConductingEquipment', 'inheritance'),
        ('normalOpen', 'bool'),
        ('retaned', 'bool'),
        ('switchOnCount', 'int'),
        ('switchOnDate', 'datetime'),
        ('ratedCurrent', 'float'),
        ('SwitchSchedules', 'reflist'),
    ],
    'Disconnector': [
        ('concrete', 'type'),
        ('Switch', 'inheritance'),
    ],
    'ProtectedSwitch': [
        ('abstract', 'type'),
        ('Switch', 'inheritance'),
        ('breakingCapacity', 'float'),
        ('SwitchSchedules', 'reflist'),
    ],
    'LoadBreakSwitch': [
        ('concrete', 'type'),
        ('ProtectedSwitch', 'inheritance'),
        ('RecloseSequences', 'reflist'),
    ],
    'Breaker': [
        ('concrete', 'type'),
        ('ProtectedSwitch', 'inheritance'),
        ('inTransitTime', 'float'),
    ],
    'BasicIntervalSchedule': [
        ('abstract', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('startTime', 'datetime'),
        ('value1Multiplier', 'UnitMultiplier'),
        ('value1Unit', 'UnitSymbol'),
        ('value2Multiplier', 'UnitMultiplier'),
        ('value2Unit', 'UnitSymbol'),
    ],
    'RegularIntervalSchedule': [
        ('abstract', 'type'),
        ('BasicIntervalSchedule', 'inheritance'),
        ('RegularTimePoints', 'reflist'),
        ('endTime', 'datetime'),
        ('timeStep', 'float'),
    ],
    'SeasonDayTypeSchedule': [
        ('abstract', 'type'),
        ('RegularIntervalSchedule', 'inheritance'),
        ('DayType', 'ref'),
        ('Season', 'ref'),
    ],
    'SwitchSchedule': [
        ('concrete', 'type'),
        ('SeasonDayTypeSchedule', 'inheritance'),
        ('Switch', 'ref'),
    ],
    'RegularTimePoint': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('IntervalSchedule', 'ref'),
        ('RegularIntervalSchedule', 'ref'),
        ('sequenceNumber', 'int'),
        ('value1', 'float'),
        ('value2', 'float'),
    ],
    'DayType': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('SeasonDayTypeSchedules', 'reflist'),
    ],
    'Season': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('SeasonDayTypeSchedules', 'reflist'),
        ('startData', 'datetime'),
        ('endData', 'datetime'),
    ],
    'RecloseSequence': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('ProtectedSwitch', 'ref'),
        ('recloseDelay', 'float'),
        ('recloseStep', 'int'),
    ],
    'Terminal': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('ConductingEquipment', 'ref'),
        ('ConnectivityNode', 'ref'),
        ('connected', 'bool'),
        ('phases', 'PhaseCode'),
        ('sequenceNumber', 'int'),
    ],
    'SeriesCompensator': [
        ('concrete', 'type'),
        ('ConductingEquipment', 'inheritance'),
        ('r', 'int'),
        ('r0', 'int'),
        ('x', 'int'),
        ('x0', 'int'),
    ],
    'Conductor': [
        ('abstract', 'type'),
        ('ConductingEquipment', 'inheritance'),
        ('length', 'int'),
    ],
    'DCLineSegment': [
        ('concrete', 'type'),
        ('Conductor', 'inheritance'),
    ],
    'ACLineSegment': [
        ('concrete', 'type'),
        ('Conductor', 'inheritance'),
        ('PerLengthImpedance', 'ref'),
        ('b0ch', 'int'),
        ('bch', 'int'),
        ('g0ch', 'int'),
        ('gch', 'int'),
        ('r', 'int'),
        ('r0', 'int'),
        ('x', 'int'),
        ('x0', 'int'),
    ],
    'PerLengthImpedance': [
        ('abstract', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('ACLineSegments', 'reflist'),
    ],
    'PerLengthPhaseImpedance': [
        ('concrete', 'type'),
        ('PerLengthImpedance', 'inheritance'),
        ('conductorCount', 'int'),
    ],
    'PerLengthSequenceImpedance': [
        ('concrete', 'type'),
        ('PerLengthImpedance', 'inheritance'),
        ('b0ch', 'int'),
        ('bch', 'int'),
        ('g0ch', 'int'),
        ('gch', 'int'),
        ('r', 'int'),
        ('r0', 'int'),
        ('x', 'int'),
        ('x0', 'int'),
    ],
    'PhaseImpedanceData': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('r', 'int'),
        ('b', 'int'),
        ('x', 'int'),
        ('sequenceNumber', 'int'),
    ],
    'ConnectivityNode': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('Terminals', 'reflist'),
        ('description', 'string'),
    ],
    'Point': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('Period', 'ref'),
        ('position', 'int'),
        ('bidQuantity', 'float'),
        ('quantity', 'float'),
    ],
    'Period': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('MarketDocument', 'ref'),
        ('Points', 'reflist'),
        ('TimeSeriess', 'reflist'),
        ('duration', 'float'),
    ],
    'Document': [
        ('abstract', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('createdDateTime', 'datetime'),
        ('lastModifiedDateTime', 'datetime'),
        ('revisionNumber', 'int'),
        ('subject', 'string'),
        ('title', 'string'),
        ('type', 'string'),
    ],
    'MarketDocument': [
        ('concrete', 'type'),
        ('Document', 'inheritance'),
        ('Period', 'reflist'),
        ('Process', 'ref'),
        ('TimeSeriess', 'reflist'),
    ],
    'Process': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('MarketDocuments', 'reflist'),
        ('classificationType', 'string'),
        ('processType', 'string'),
    ],
    'MeasurementPoint': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('TimeSeries', 'ref'),
    ],
    'TimeSeries': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('MarketDocument', 'ref'),
        ('Period', 'ref'),
        ('MeasurementPoints', 'reflist'),
        ('objectAggregation', 'string'),
        ('product', 'string'),
        ('version', 'string'),
    ],
    'IrregularIntervalSchedule': [
        ('abstract', 'type'),
        ('BasicIntervalSchedule', 'inheritance'),
        ('IrregularTimePoints', 'reflist'),
    ],
    'OutageSchedule': [
        ('concrete', 'type'),
        ('IrregularIntervalSchedule', 'inheritance'),
        ('PowerSystemResource', 'ref'),
    ],
    'IrregularTimePoint': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('IrregularIntervalSchedule', 'ref'),
        ('time', 'float'),
        ('value1', 'float'),
        ('value2', 'float'),
    ],
    'CurveData': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('Curve', 'ref'),
        ('xvalue', 'float'),
        ('y1value', 'float'),
        ('y2value', 'float'),
        ('y3value', 'float'),
    ],
    'Curve': [
        ('concrete', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('CurveDatas', 'reflist'),
        ('curveStyle', 'CurveStyle'),
        ('xMultiplier', 'UnitMultiplier'),
        ('xUnit', 'UnitSymbol'),
        ('y1Multiplier', 'UnitMultiplier'),
        ('y1Unit', 'UnitSymbol'),
        ('y2Multiplier', 'UnitMultiplier'),
        ('y2Unit', 'UnitSymbol'),
        ('y3Multiplier', 'UnitMultiplier'),
        ('y3Unit', 'UnitSymbol'),
    ],
    'TransformerEnd': [
        ('abstract', 'type'),
        ('IdentifiedObject', 'inheritance'),
        ('RatioTapChanger', 'ref'),
        ('endNumber', 'int'),
        ('grounded', 'bool'),
    ],
    'PowerTransformerEnd': [
        ('concrete', 'type'),
        ('TransformerEnd', 'inheritance'),
        ('PowerTransformer', 'ref'),
        ('connectionKind', 'WindingConnection'),
        ('phaseAngleClock', 'int'),
        ('ratedS', 'int'),
        ('ratedU', 'int'),
        ('b', 'int'),
        ('b0', 'int'),
        ('g', 'int'),
        ('g0', 'int'),
        ('r', 'int'),
        ('r0', 'int'),
        ('x', 'int'),
        ('x0', 'int'),
    ],
    'TapChanger': [
        ('abstract', 'type'),
        ('PowerSystemResource', 'inheritance'),
        ('highStep', 'int'),
        ('initialDelay', 'int'),
        ('lowStep', 'int'),
        ('ltcFlag', 'bool'),
        ('neutralStep', 'int'),
        ('neutralU', 'int'),
        ('normalStep', 'int'),
        ('regulationStatus', 'bool'),
        ('subsequentDelay', 'int'),
    ],
    'RatioTapChanger': [
        ('concrete', 'type'),
        ('TapChanger', 'inheritance'),
        ('TransformerEnds', 'reflist'),
        ('StepVoltageIncrement', 'int'),
        ('tculControlMode', 'TransformerControlMode'),
    ],
    'PowerTransformer': [
        ('concrete', 'type'),
        ('ConductingEquipment', 'inheritance'),
        ('PowerTransformerEnds', 'reflist'),
        ('VectorGroup', 'string'),
    ],
}

classes = [x for x, y in models.items()]
